apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  labels:
    app: test-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
      - name: test-api
        image: jrios304/test-api:latest
        ports:
        - containerPort: 8000
        # Recursos obligatorios para que el HPA funcione
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        # K8s solo envía tráfico cuando el pod está listo
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        # K8s reinicia el pod si deja de responder
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3